### ISSUE TITLE
InputManager

### ISSUE THREAD

**Issue by DzintarsApeinans** [JohnnyTurbo/Gauntlet#1]
Hello, I downloaded your project to check gameplay, but couldn't play it because there is problem with -> Input Axis Controller2Horizontal is not setup. How you setted them, so i could check gameplay and learn something new from your game. Same problem with -> Input Button Controller1Attack is not setup. Could i get your InputManager details?

**Comment by JohnnyTurbo** [comment]
Hello, thanks for taking interest in my project. The input manager is pretty complicated as it supports up to four separate players, so I have attached the input manager file. Just unzip the file and replace the InputManager.asset in the ProjectSettings folder and you should be good to go.

The Input manager is setup to work with PS4 controllers, the left stick controls player movement, the X button is attack and O uses a potion. You can also use the keyboard to control each player, helpful for debugging. Movement is WASD for P1, TFGH for P2, IJKL for P3, and arrow keys for P4. Attack and Item for players respectively are Q E for P1, R Y for P2, U O for P3, and right ctrl and num pad 0 for p4.

Let me know if you have any further questions or need help understanding anything, I'm happy to help!

[InputManager.zip](https://github.com/JohnnyTurbo/Gauntlet/files/346865/InputManager.zip)

**Comment by DzintarsApeinans** [comment]
Thank you, everything works fine now.
